Update article.md
trueberryless-org/mutanuq pull request #19
Opened 2023-11-08 16:38 UTC by bonkastinator

finished article summary in german
not sure it looks like it should

2023-11-08 17:24 UTC, trueberryless requested changes
Grundsätzlich passt alles, hier und da bin ich leider etwas penible und würde deswegen ein paar Änderungen vorschlagen.

2023-11-08 17:24 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +>**Involving the reader:**
```suggestion
### Involving the reader
```

Ich würde das als Überschrift machen

2023-11-08 17:24 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +>Have you ever...?
```suggestion
> Have you ever...?
```

und hier brauchst du überall ein Leerzeichen

2023-11-08 17:24 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +:::note
Diese Note müsste sich auch irgendwann wieder schließen, indem du `:::` verwendest

2023-11-08 17:24 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +1. **Der Artikel braucht eine kreative Überschrift**, die den Leser anregt, den Rest zu lesen. Ein schlechtes Beispiel ist "school uniforms", ein positiveres Beispiel wäre in diesem Fall "why school
```suggestion
1. Der Artikel braucht eine **kreative Überschrift**, die den Leser anregt, den Rest zu lesen. Ein schlechtes Beispiel ist "school uniforms", ein positiveres Beispiel wäre in diesem Fall "why school uniforms are outdated". Mit einer Frage fängt man Leser sehr einfach.
```

Persönlich würde ich nur so wenig Wörter wie möglich fett markieren. Wenn du willst, kannst du auch Überschriften aus der nummerierten Liste machen, dann musst du auch nicht so viel fett machen.

2023-11-08 17:24 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +#### Zusammenfassung
```suggestion
## Zusammenfassung
```

Ich würde hier mit einer "Zweier Überschrift" anfange, sry, das ist vielleicht bissl verwirrend, weil ich bei Todo eine vierer Überschrift verwendet habe...

2023-11-08 20:31 UTC, bonkastinator reviewed
solltat alles gmacht ham

2023-11-09 20:05 UTC, trueberryless approved these changes

2023-11-12 09:48 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +Der Article ist eine einfache Textsorte, bei der vor allem die kreative Schreibweise benötigt wird, da es sehr wenige Vorgaben gibt. Wichtig ist:
```suggestion
Der Artikel ist eine einfache Textsorte, bei der vor allem die kreative Schreibweise benötigt wird, da es sehr wenige Vorgaben gibt. Wichtig ist:
```

2023-11-12 09:49 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +Auch wenn man den Leser "fangen" soll, so sollte man nicht zu sehr in den clickbait stil verfallen. :::
```suggestion
Auch wenn man den Leser "fangen" soll, so sollte man nicht zu sehr in den clickbait stil verfallen. 
:::
```

2023-11-12 09:49 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +Auch wenn man den Leser "fangen" soll, so sollte man nicht zu sehr in den clickbait stil verfallen.
```suggestion
Auch wenn man den Leser "fangen" soll, so sollte man nicht zu sehr in den Clickbait-Stil verfallen. 
```

2023-11-12 09:50 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +2. **Sprich den Leser an.** Am einfachsten geht das mit rhetorischen Fragen und direkter anrede, wie beispielsweise "What do you think about..."
```suggestion
2. **Sprich den Leser an.** Am einfachsten geht das mit rhetorischen Fragen und direkter Anrede, wie beispielsweise "What do you think about..."
```

2023-11-12 09:51 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +- Have you ever...?
```suggestion

- Have you ever...?
```

2023-11-12 09:51 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +## Phrasen
```suggestion
## Phrasen

```

2023-11-12 09:51 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +### Giving opinions:
```suggestion
### Giving opinions

```

2023-11-12 09:53 UTC, trueberryless commented on starlight/src/content/docs/de/languages/text_types/article.md
> +### Involving the reader:
```suggestion
### Involving the reader
```

2023-11-12 09:54 UTC, merged